/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MyFirstService.h"
#include "MyFirstService.tcc"




MyFirstService_ping_args::~MyFirstService_ping_args() noexcept {
}


MyFirstService_ping_pargs::~MyFirstService_ping_pargs() noexcept {
}


MyFirstService_ping_result::~MyFirstService_ping_result() noexcept {
}


MyFirstService_ping_presult::~MyFirstService_ping_presult() noexcept {
}


MyFirstService_log_args::~MyFirstService_log_args() noexcept {
}


MyFirstService_log_pargs::~MyFirstService_log_pargs() noexcept {
}


MyFirstService_multiply_args::~MyFirstService_multiply_args() noexcept {
}


MyFirstService_multiply_pargs::~MyFirstService_multiply_pargs() noexcept {
}


MyFirstService_multiply_result::~MyFirstService_multiply_result() noexcept {
}


MyFirstService_multiply_presult::~MyFirstService_multiply_presult() noexcept {
}


MyFirstService_get_log_size_args::~MyFirstService_get_log_size_args() noexcept {
}


MyFirstService_get_log_size_pargs::~MyFirstService_get_log_size_pargs() noexcept {
}


MyFirstService_get_log_size_result::~MyFirstService_get_log_size_result() noexcept {
}


MyFirstService_get_log_size_presult::~MyFirstService_get_log_size_presult() noexcept {
}


MyFirstService_send_binary_args::~MyFirstService_send_binary_args() noexcept {
}


MyFirstService_send_binary_pargs::~MyFirstService_send_binary_pargs() noexcept {
}



